[package]
name = "FeedMee"
description = "The seriously fast feed reader."
authors = ["dcog989"]
edition = "2024"
license = "MIT"
version = "0.19.1"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "feedmee_lib"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
async-trait = "0.1"
base64 = "0.23"
chrono = { version = "0.4", features = [] }
feed-rs = "2.4"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
log = "0.4"
opml = "1.1"
readabilityrs = "0.1"
reqwest = { version = "0.13", features = ["json", "rustls"] }
rusqlite = { version = "0.40", features = ["bundled"] }
rusqlite_migration = "2.6"
scraper = "0.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.12"
tauri = { version = "2.11", features = [] }
tauri-plugin-dialog = "2.7"
tauri-plugin-fs = "2.5"
tauri-plugin-opener = "2.5"
tauri-plugin-updater = "2.10"
tauri-plugin-window-state = "2.4"
toml = "1.1"
url = "2.5"
webp = "0.3.1"

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
strip = true
