[package]
name = "FeedMee"
version = "0.6.1"
description = "The seriously fast feed reader."
edition = "2024"
authors = ["dcog989"]

[lib]
name = "feedmee_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
chrono = "0.4"
feed-rs = "2.3"
generic-array = "1.4"
log = "0.4"
opml = "1.1"
readabilityrs = "0.1"
reqwest = { version = "0.13", features = ["json", "rustls", "blocking"] }
rusqlite = { version = "0.39", features = ["bundled"] }
rusqlite_migration = "2.5"
scraper = "0.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.12"
tauri = { version = "2.11", features = [] }
tauri-plugin-dialog = "2.7"
tauri-plugin-fs = "2.5"
tauri-plugin-opener = "2.5"
tauri-plugin-updater = "2"
toml = "1.1"
url = "2.5"
tauri-plugin-window-state = "2.4"
