import type { AppSettings, Article, Folder } from './types';

export type Theme = 'light' | 'dark' | 'sepia' | 'system';
export type SortOrder = 'desc' | 'asc';

export interface AppState {
    folders: Folder[];
    articles: Article[];
    selectedFeedId: number | null;
    selectedFolderId: number | null;
    selectedArticle: Article | null;
    isLoadingArticles: boolean;
    isRefreshingFeeds: boolean;
    searchQuery: string;
    theme: Theme;
    sortOrder: SortOrder;
    settings: AppSettings;
    showSettings: boolean;
    showAddDialog: boolean;
    expandedFolders: Set<number>;
    focusedPane: 'nav' | 'list' | 'reading';
    customShortcuts: Record<string, string>;
    navWidth: number;
    listWidth: number;
    page: number;
    readonly pageSize: number;
    hasMore: boolean;
    latestHours: number;
    lastRefreshed: Map<number, number>;
    updatingFeedIds: Set<number>;
    modalState: {
        isOpen: boolean;
        type: 'confirm' | 'alert';
        message: string;
        onConfirm: () => void;
    };
    readonly debounceMs: number;
    isFeedFresh(feedId: number): boolean;
    isFolderFresh(folderId: number): boolean;
    isAllFresh(): boolean;
    isFeedUpdating(feedId: number): boolean;
    isFolderUpdating(folderId: number): boolean;
    refreshFolders(): Promise<void>;
    reloadCurrentArticleList(): Promise<void>;
    refreshAllFeeds(): Promise<void>;
    requestRefreshFeed(feedId: number): Promise<void>;
    requestRefreshFolder(folderId: number): Promise<void>;
    selectFeed(feedId: number): Promise<void>;
    selectFolder(folderId: number): Promise<void>;
    selectArticle(article: Article): void;
    toggleSaved(article: Article): Promise<void>;
    fetchFullContent(article: Article): Promise<string | null>;
    loadMore(): Promise<void>;
    markAllRead(): Promise<void>;
    addFeed(url: string, folderId?: number | null): Promise<void>;
    createFolder(name: string): Promise<void>;
    importOpml(): Promise<void>;
    exportOpml(): Promise<void>;
    renameFolder(id: number, newName: string): Promise<void>;
    renameFeed(id: number, newName: string): Promise<void>;
    deleteFeed(id: number): Promise<void>;
    deleteFolder(id: number): Promise<void>;
    moveFeed(feedId: number, folderId: number): Promise<void>;
    navUp(): void;
    navDown(): void;
    articleUp(): void;
    articleDown(): void;
    setShortcut(commandId: string, key: string): void;
    resetShortcut(commandId: string): void;
    setSortOrder(order: SortOrder): Promise<void>;
    setSearch(query: string): Promise<void>;
    setTheme(theme: Theme): void;
    openSettings(): void;
    closeSettings(): void;
    saveSettings(newSettings: AppSettings, closeModal?: boolean): Promise<void>;
    confirm(message: string, onConfirm: () => void): void;
    alert(message: string): void;
    closeModal(): void;
}
